# Generated by Django 4.2.4 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0002_game_game_id_game_iscompleted_schedule_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(default=99),
        ),
    ]
