# Generated by Django 4.2.4 on 2023-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0003_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='sched', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.CharField(default='logo', max_length=200),
            preserve_default=False,
        ),
    ]
