# Generated by Django 4.2.4 on 2023-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0005_prediction_away_team_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('games', models.ManyToManyField(to='prob_model.game')),
            ],
        ),
    ]
