# Generated by Django 4.2.4 on 2023-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0006_gameset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostRecentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
            ],
        ),
    ]
