# Generated by Django 4.2.4 on 2023-08-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0008_mostrecentday_rd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
