# Generated by Django 4.2.4 on 2023-08-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0011_modelinfo_my_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinfo',
            old_name='my_id',
            new_name='name',
        ),
    ]
