# Generated by Django 4.2.4 on 2023-08-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_model', '0012_rename_my_id_modelinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinfo',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
